ARG IMAGE_REGISTRY=registry.cn-shanghai.aliyuncs.com/zhinian-software
ARG IMAGE_TAG=latest
FROM ${IMAGE_REGISTRY}/xianyu-websocket:${IMAGE_TAG}
WORKDIR /app
COPY common /app/common
COPY websocket /app/websocket
