ARG IMAGE_REGISTRY=registry.cn-shanghai.aliyuncs.com/zhinian-software
ARG IMAGE_TAG=latest
FROM ${IMAGE_REGISTRY}/xianyu-scheduler:${IMAGE_TAG}
WORKDIR /app
COPY common /app/common
COPY scheduler /app/scheduler
COPY backend-web /app/backend-web
